name: Connection Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Basic Test
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "API Key exists: ${{ secrets.ANTHROPIC_API_KEY != '' }}"
          echo "GitHub Token exists: ${{ secrets.GITHUB_TOKEN != '' }}"
        
      - name: Claude Action Test (最小)
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: "Hello, please respond with 'Connection successful'"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
