name: Claude Emergency Fix

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Emergency Fix
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: "Fix MissingReferenceException in UpgradeSidePanelUI.cs"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
